version: '3'
services:
    db:
        image: postgres:11.7
        environment:
            - POSTGRES_PASSWORD=loginpage
            - POSTGRES_USER=postgres
            - POSTGRES_DB=loginpage
        ports:
            - 5432:5432