version: "3"
volumes:
  dados:
networks:
  db:
  web:
services:
  db:
    image: postgres:11.7
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      #- ./scripts:/scripts
      #- ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=loginpage
      - POSTGRES_USER=postgres
      - POSTGRES_DB=loginpage
    ports:
      - 5433:5432
    networks:
      - db
    depends_on:
      - backend
  frontend:
    image: nginx:1.18.0
    volumes:
      #Site
      - ./frontend/dist:/usr/share/nginx/html
      #Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    depends_on:
      - backend
  backend:
    image: node:12.16.2
    volumes:
      - ./backend:/backend
    command: bash -c "cd backend && npm i && npx sequelize db:seed:undo:all && npx sequelize db:migrate:undo:all && npx sequelize db:migrate && npx sequelize db:seed:all && node src/server.js"
    networks:
      - db
      - web
